name: Docker CI

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set lowercase repository name
        run: |
          echo "REPO_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build image
        run: cd TP10 && docker build -t ghcr.io/${{ env.REPO_OWNER }}/app:${{ github.sha }} .

      - name: Run tests
        run: cd TP10 && docker compose run --rm test

      - name: Scan image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ env.REPO_OWNER }}/app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'

      - name: Generate SBOM
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy image --format cyclonedx --output sbom.json ghcr.io/${{ env.REPO_OWNER }}/app:${{ github.sha }}

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

      - name: Push to GitHub Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ env.REPO_OWNER }}/app:${{ github.sha }}
